# Generated by Django 5.0.2 on 2024-03-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='playeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
