# Generated by Django 5.0.2 on 2024-03-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_playeruser_options_alter_playeruser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='playeruser',
            name='last_name',
        ),
    ]
