# Generated by Django 5.0.2 on 2024-03-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_playeruser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerUser',
        ),
    ]
