# Generated by Django 5.0.2 on 2024-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'Generate Core data'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='last_update',
            field=models.DateTimeField(default="2024-03-07 22:00"),
            preserve_default=False,
        ),
    ]
