# Generated by Django 5.0.2 on 2024-03-06 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_goods_recipe_recipe_goods_recipe_required_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_assigned', models.BooleanField(default=False)),
                ('active_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workshop')),
            ],
        ),
    ]
