# Generated by Django 5.0.2 on 2024-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_recipe_required_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
