# Generated by Django 5.0.2 on 2024-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'Generate Core data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_goods',
            name='max_stack_size',
            field=models.IntegerField(default=20),
        ),
    ]
