# Generated by Django 5.0.2 on 2024-03-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
            preserve_default=False,
        ),
    ]
