# Generated by Django 5.0.2 on 2024-03-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='constructed_goods',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='required_goods',
            field=models.ManyToManyField(related_name='+', through='core.Recipe_Goods', to='core.goods'),
        ),
    ]
