# Generated by Django 5.0.2 on 2024-03-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number_of_spaces',
        ),
        migrations.AddField(
            model_name='storage',
            name='number_of_storage_spaces',
            field=models.IntegerField(default=1),
        ),
    ]
