# Generated by Django 5.0.2 on 2024-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'Generate Core data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='travel_speed_per_block',
            field=models.IntegerField(default=20),
        ),
    ]
