# Generated by Django 5.0.2 on 2024-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'Generate Core data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='familyName',
        ),
        migrations.AddField(
            model_name='character',
            name='firstName',
            field=models.CharField(default='john', max_length=200),
            preserve_default=False,
        ),
    ]
