# Generated by Django 5.0.2 on 2024-03-07 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_country_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='country',
            name='tick_in_seconds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='country',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
