# Generated by Django 5.0.2 on 2024-03-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_cart_travel_speed_per_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
