# Generated by Django 5.0.2 on 2024-03-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_country_start_date_country_tick_in_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='construction_ticks',
            field=models.IntegerField(default=20),
        ),
    ]
