# Generated by Django 5.0.2 on 2025-02-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_item_information_cart_carried_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="carried_items",
        ),
        migrations.AlterUniqueTogether(
            name="cart_storage",
            unique_together={("cart", "item_information")},
        ),
    ]
