# Generated by Django 5.0.2 on 2025-02-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_workshop_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="name",
            field=models.CharField(default="Workshop", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshop",
            name="profession",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.professioninformation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="location_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.building",
            ),
        ),
    ]
