# Generated by Django 5.0.2 on 2025-02-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_workshop_name_workshop_profession_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="location_id",
            new_name="current_location",
        ),
    ]
